### ISSUE TITLE
Properly version images

### ISSUE THREAD

**Issue by acollierr17** [suggestionsbot/suggestions-bot-js#26]
Each stable release should not only push an image with the `latest` tag but also an image with the version for that image (ex. `v2.9.7`)

**Comment by alaninnovates** [comment]
I am not exactly sure, but can't you change this
https://github.com/suggestionsbot/suggestions-bot/blob/bb0decf96fb899c97d7c8eb59c6a52cff6139df4/.github/workflows/publish-image.yml#L21
to 
```
tags: latest,${{ github.event.release.tag_name }}
```
I am not exactly sure if this works, but I think it should. (I didn't PR because I didn't test it)

Source of info: [Github docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-36)

**Comment by acollierr17** [comment]
> I am not exactly sure, but can't you change this
> 
> https://github.com/suggestionsbot/suggestions-bot/blob/bb0decf96fb899c97d7c8eb59c6a52cff6139df4/.github/workflows/publish-image.yml#L21
> 
> 
> to
> ```
> tags: latest,${{ github.event.release.tag_name }}
> ```
> 
> I am not exactly sure if this works, but I think it should. (I didn't PR because I didn't test it)
> 
> Source of info: [Github docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-36)

This is a start and actually reminded me to get back to this. So I thank you for that!

I would say this is close to the proper usage. The only thing off is the syntax and that I looked into. 

The [advanced usage](https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md) section from https://github.com/docker/build-push-action helped for starters. Also, [`flavor` input](https://github.com/marketplace/actions/docker-metadata-action#flavor-input) from https://github.com/docker/metadata-action was also useful.

I'll do some testing and tweaking to make sure releases are properly integrated with all this. But I think I have a solid start to things.
